### ISSUE TITLE
[oc_folders] RLV attachements in the Owners HUD bug

### ISSUE THREAD

**Issue by Aaack-Aardvark** [lickx/oscollar-dev#83]
When you add something from the RLV folder from the owners HUD it does it but it appears as only partially added, you have to add it a second time to get the proper status on the dialog.

Same thing happens when remove the item.

**Comment by lickx** [comment]
That is most likely because you're on OsGrid which has an extremely slow inventory server. The items are attaching, but that doesn't reflect in the button because OsGrid is at that time still populating the current outfit folder with the to-be-attached items. After a folder is attached, the script sleeps for 1 second for inventory to populate, then does "getinvworn:"+g_sCurrentFolder which doesn't return all items cos OsGrid is slow as hell.

You can work around this by setting a longer delay on line 557 so it becomes:
```
                    if (sMessage != UPMENU) {
                        addToHistory(g_sCurrentFolder);
                        llSleep(3.0); // original is 1.0
                    }
```

**Comment by lickx** [comment]
Since this is a grid speed issue I am closing this
